# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
xcode_project: ContextLabel.xcodeproj
xcode_scheme: ContextLabel
xcode_sdk: iphonesimulator9.0

script: xctool test -project ContextLabel.xcodeproj -scheme ContextLabel -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO